client openvpn {
    ipaddr = 10.10.20.201  # OpenVPN container IP in internal_net
    secret = testing123
    shortname = openvpn
}

client dockernet {
    ipaddr = 10.10.0.0/16
    secret = testing123
    shortname = dockernet
}
